md account
md alliances
md bloodlines
md characters",
md constellations
md corporation
md corporation\npcCorporation
md dogma
md dogma\attribute
md dogma\effects
md fleet
md fleet\fleets
md fleet\fleets\wings
md fleet\fleets\wings\squads
md fleet\fleets\members
md incursions
md industry
md industry\facility
md industry\system
md inventory
md inventory\categories
md inventory\groups
md inventory\types
md map
md market
md market\groups
md market\prices
md market\types
md opportunity
md opportunity\groups
md opportunity\tasks
md sovereignty
md sovereignty\campaigns
md sovereignty\structures
md races
md regions
md schema
md schema\endpoints
md schema\options
md tournaments
md tournaments\tournaments
md tournaments\tournaments\tournament
md tournaments\tournaments\tournament\series
md tournaments\tournaments\tournament\series\bans
md tournaments\tournaments\tournament\series\matches
md tournaments\tournaments\tournament\series\matches\match
md tournaments\tournaments\tournament\series\matches\match\static
md tournaments\tournaments\tournament\series\matches\match\pilotStats
md tournaments\tournaments\tournament\series\matches\match\realtime
md tournaments\tournaments\tournament\series\matches\match\realtime\frame
md tournaments\tournaments\tournament\teams
md tournaments\tournaments\tournament\team
md tournaments\tournaments\teams
md tournaments\tournaments\teams\team
md tournaments\tournaments\teams\team\memebers

md solarsystems
md time
md decode
md virtualGoodStore
md wars

